// Re-export the React Navigation fork's public surface. Expo Router intentionally
// shadows several names with its own wrappers/types, so they are omitted here:
//   - `useNavigation`, `useFocusEffect`, `useIsFocused`, `useNavigationContainerRef`
//     (Expo Router wrappers are re-exported from `src/exports.ts`)

export {
  BaseNavigationContainer,
  createComponentForStaticNavigation,
  createNavigationContainerRef,
  createPathConfigForStaticNavigation,
  CurrentRenderContext,
  findFocusedRoute,
  getActionFromState,
  getFocusedRouteNameFromRoute,
  getPathFromState,
  getStateFromPath,
  NavigationContainerRefContext,
  NavigationContext,
  NavigationHelpersContext,
  NavigationIndependentTree,
  NavigationMetaContext,
  NavigationProvider,
  NavigationRouteContext,
  PreventRemoveContext,
  PreventRemoveProvider,
  PrivateValueStore,
  ThemeContext,
  ThemeProvider,
  useNavigationIndependentTree,
  usePreventRemoveContext,
  useStateForPath,
  validatePathConfig,
  DarkTheme,
  DefaultTheme,
  useTheme,
  usePreventRemove,
  LinkingContext,
  LocaleDirContext,
  ServerContainer,
  UNSTABLE_UnhandledLinkingContext,
  useLinkBuilder,
  useLocale,
  useRoutePath,
  useRoute,
  useScrollToTop,
  useNavigationState,
  createNavigatorFactory,
  useNavigationBuilder,
  BaseRouter,
  CommonActions,
  DrawerActions,
  DrawerRouter,
  StackActions,
  StackRouter,
  TabActions,
  TabRouter,
  type StaticConfig,
  type StaticConfigGroup,
  type StaticConfigScreens,
  type StaticNavigation,
  type StaticParamList,
  type StaticScreenProps,
  type DrawerActionHelpers,
  type DrawerActionType,
  type DrawerNavigationState,
  type DrawerRouterOptions,
  type DrawerStatus,
  type StackActionHelpers,
  type StackActionType,
  type StackNavigationState,
  type StackRouterOptions,
  type TabActionHelpers,
  type TabActionType,
  type TabNavigationState,
  type TabRouterOptions,
} from './native';

export type * from './core/types';
export type * from './native/types';
export type * from './native-stack/types';

export * from './elements';

export type {
  ActionCreators,
  CommonNavigationAction,
  DefaultRouterOptions,
  InitialState,
  NavigationAction,
  NavigationRoute,
  NavigationState,
  ParamListBase,
  PartialRoute,
  PartialState,
  Route,
  Router,
  RouterConfigOptions,
  RouterFactory,
} from './routers/types';
